# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Node.js LTS Alpine as base image
FROM node:lts-alpine

# Set working directory to /app
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy the entire repository so that extended tsconfig and sources are available
COPY . .

# Build the brave-search server
WORKDIR /app/src/brave-search
RUN npx tsc

# Reset working directory to /app for runtime
WORKDIR /app

# Run the brave-search server using absolute path
CMD [ "node", "/app/src/brave-search/dist/index.js" ]
